# fly.toml app configuration file generated for coin-gift-app on 2025-10-07T11:22:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coin-gift-app'
primary_region = 'fra'
swap_size_mb = 2048

[build]

[env]
  DATABASE_URL = '/data/sqlite.db'

[[mounts]]
  source = 'db_data'
  destination = '/data'
  initial_size = '1'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '5GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
